Code to separeta tagged images in zooniverse in the different classes needed

In [ ]:
import pandas as pd
import sys
import os

In [ ]:
sys.path.insert(0, "../../")
from config import CROPPED_PATH
CSV_FILE_PATH = "/home/nicolas/Descargas/automating-allium-cepa-assay-analysis-with-ai-classifications.csv"
CROPS_PATH = os.path.join(CROPPED_PATH, 'classification')

In [18]:
df = pd.read_csv(CSV_FILE_PATH)

In [19]:
df.head()

,classification_id,user_name,user_id,user_ip,workflow_id,workflow_name,workflow_version,created_at,gold_standard,expert,metadata,annotations,subject_data,subject_ids
0,651783183,Nictauro,2892598.0,49301c690bcf4d3b3a13,29297,Mitosis Stage Classify,10.2,2025-07-09 12:47:14 UTC,NaN,NaN,"{""source"":""api"",""session"":""25b331a762b4ab010f1...","[{""task"":""T0"",""task_label"":""I which stage of m...","{""110828150"":{""retired"":null,""Filename"":""A_15_...",110828150
1,651783233,Nictauro,2892598.0,49301c690bcf4d3b3a13,29297,Mitosis Stage Classify,10.2,2025-07-09 12:47:29 UTC,NaN,NaN,"{""source"":""api"",""session"":""25b331a762b4ab010f1...","[{""task"":""T0"",""task_label"":""I which stage of m...","{""110828208"":{""retired"":null,""Filename"":""A_21_...",110828208
2,651783245,Nictauro,2892598.0,49301c690bcf4d3b3a13,29297,Mitosis Stage Classify,10.2,2025-07-09 12:47:33 UTC,NaN,NaN,"{""source"":""api"",""session"":""25b331a762b4ab010f1...","[{""task"":""T0"",""task_label"":""I which stage of m...","{""110828153"":{""retired"":null,""Filename"":""A_15_...",110828153
3,651783364,Nictauro,2892598.0,49301c690bcf4d3b3a13,29297,Mitosis Stage Classify,10.2,2025-07-09 12:47:54 UTC,NaN,NaN,"{""source"":""api"",""session"":""25b331a762b4ab010f1...","[{""task"":""T0"",""task_label"":""I which stage of m...","{""110828211"":{""retired"":null,""Filename"":""A_22_...",110828211
4,651783392,Nictauro,2892598.0,49301c690bcf4d3b3a13,29297,Mitosis Stage Classify,10.2,2025-07-09 12:47:59 UTC,NaN,NaN,"{""source"":""api"",""session"":""25b331a762b4ab010f1...","[{""task"":""T0"",""task_label"":""I which stage of m...","{""110828203"":{""retired"":null,""Filename"":""A_20_...",110828203

In [20]:
annotations_subject_data = df[['annotations', 'subject_data']]
annotations_subject_data.head()

,annotations,subject_data
0,"[{""task"":""T0"",""task_label"":""I which stage of m...","{""110828150"":{""retired"":null,""Filename"":""A_15_..."
1,"[{""task"":""T0"",""task_label"":""I which stage of m...","{""110828208"":{""retired"":null,""Filename"":""A_21_..."
2,"[{""task"":""T0"",""task_label"":""I which stage of m...","{""110828153"":{""retired"":null,""Filename"":""A_15_..."
3,"[{""task"":""T0"",""task_label"":""I which stage of m...","{""110828211"":{""retired"":null,""Filename"":""A_22_..."
4,"[{""task"":""T0"",""task_label"":""I which stage of m...","{""110828203"":{""retired"":null,""Filename"":""A_20_..."

In [21]:
import json

def extract_value(annotation_str):
    annotation_list = json.loads(annotation_str)
    return annotation_list[0]['value'] if annotation_list and 'value' in annotation_list[0] else None

# 2. Define a function to extract the filename
def extract_filename(subject_data_str):
    """
    Parses a JSON string from the 'subject_data' column
    and extracts the 'Filename' value from the nested dictionary.
    """
    if not isinstance(subject_data_str, str):
        return None
    try:
        # Load the string as a JSON object
        data = json.loads(subject_data_str)
        if not data:
            return None # Handles empty JSON object '{}'
            
        # The outer dictionary has a dynamic key. We get its value,
        # which is the inner dictionary.
        inner_dict = next(iter(data.values()))
        
        # Return the value of the 'Filename' key, or None if it doesn't exist
        return inner_dict.get('Filename')
    except (json.JSONDecodeError, StopIteration, AttributeError):
        # Handle cases where the string is not valid JSON,
        # or doesn't have the expected structure.
        return None

annotations_subject_data['stage'] = annotations_subject_data['annotations'].apply(extract_value)
annotations_subject_data['filename'] = annotations_subject_data['subject_data'].apply(extract_filename)
annotations_subject_data.head()

/tmp/ipykernel_231409/2245068582.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  annotations_subject_data['stage'] = annotations_subject_data['annotations'].apply(extract_value)
/tmp/ipykernel_231409/2245068582.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  annotations_subject_data['filename'] = annotations_subject_data['subject_data'].apply(extract_filename)

,annotations,subject_data,stage,filename
0,"[{""task"":""T0"",""task_label"":""I which stage of m...","{""110828150"":{""retired"":null,""Filename"":""A_15_...",Prophase,A_15_10.png
1,"[{""task"":""T0"",""task_label"":""I which stage of m...","{""110828208"":{""retired"":null,""Filename"":""A_21_...",Interphase,A_21_63.png
2,"[{""task"":""T0"",""task_label"":""I which stage of m...","{""110828153"":{""retired"":null,""Filename"":""A_15_...",Prophase,A_15_23.png
3,"[{""task"":""T0"",""task_label"":""I which stage of m...","{""110828211"":{""retired"":null,""Filename"":""A_22_...",Metaphase,A_22_43.png
4,"[{""task"":""T0"",""task_label"":""I which stage of m...","{""110828203"":{""retired"":null,""Filename"":""A_20_...",Anaphase,A_20_66.png

In [22]:
results = annotations_subject_data[['stage', 'filename']]
results.head()

        stage     filename
0    Prophase  A_15_10.png
1  Interphase  A_21_63.png
2    Prophase  A_15_23.png
3   Metaphase  A_22_43.png
4    Anaphase  A_20_66.png

In [23]:
cleaned_results = results.groupby('filename')['stage'].agg(lambda x: x.mode()[0]).reset_index()


# 3. Display the final, cleaned DataFrame
print("Cleaned DataFrame:")
cleaned_results.head()

Cleaned DataFrame:

            filename                    stage
0   001_00026_86.png               Not a cell
1  001_00027_179.png  Chromosomal aberrations
2   001_00027_52.png               Not a cell
3   001_00027_55.png               Interphase
4   001_00027_80.png            Indeterminate

In [37]:
import os
import shutil
stage_to_filenames_dict = cleaned_results.groupby('stage')['filename'].apply(list).to_dict()

print("DataFrames were separated into a dictionary.\n")
print(f"Available stages: {list(stage_to_filenames_dict.keys())}")
print("-" * 35)

for stage in list(stage_to_filenames_dict.keys()):
    os.makedirs(os.path.join(CROPS_PATH, stage), exist_ok=True)
    for image in stage_to_filenames_dict[stage]:
        src = os.path.join(CROPS_PATH, image)
        dst = os.path.join(CROPS_PATH, stage, image)
        if os.path.exists(src):
            os.rename(src, dst)
            # shutil.copy2(src, dst)
            print(f"Moved {image} to {stage} folder.")
        else:
            print(f"Source file {src} does not exist. Skipping.")

DataFrames were separated into a dictionary.

Available stages: ['Anaphase', 'Chromosomal aberrations', 'Indeterminate', 'Interphase', 'Metaphase', 'Not a cell', 'Prophase', 'Telophase']
-----------------------------------
Moved 002_00058_24.png to Anaphase folder.
Moved 003_00002_8.png to Anaphase folder.
Moved 003_00009_106.png to Anaphase folder.
Moved 004_00051_122.png to Anaphase folder.
Moved 004_00070_113.png to Anaphase folder.
Moved A_10_72.png to Anaphase folder.
Moved A_115_137.png to Anaphase folder.
Moved A_12_82.png to Anaphase folder.
Moved A_12_84.png to Anaphase folder.
Moved A_14_18.png to Anaphase folder.
Moved A_14_42.png to Anaphase folder.
Moved A_14_83.png to Anaphase folder.
Moved A_15_27.png to Anaphase folder.
Moved A_17_3.png to Anaphase folder.
Moved A_17_80.png to Anaphase folder.
Moved A_17_85.png to Anaphase folder.
Moved A_17_89.png to Anaphase folder.
Moved A_17_96.png to Anaphase folder.
Moved A_20_66.png to Anaphase folder.
Moved A_21_9.png to Anaphase folder.
Moved A_248_24.png to Anaphase folder.
Moved A_24_21.png to Anaphase folder.
Moved A_289_45.png to Anaphase folder.
Moved A_290_51.png to Anaphase folder.
Moved A_291_54.png to Anaphase folder.
Moved A_298_75.png to Anaphase folder.
Moved A_2_43.png to Anaphase folder.
Moved A_2_44.png to Anaphase folder.
Moved A_306_44.png to Anaphase folder.
Moved A_309_75.png to Anaphase folder.
Moved A_315_10.png to Anaphase folder.
Moved A_328_40.png to Anaphase folder.
Moved A_332_26.png to Anaphase folder.
Moved A_338_47.png to Anaphase folder.
Moved A_346_52.png to Anaphase folder.
Moved A_62_41.png to Anaphase folder.
Moved A_70_101.png to Anaphase folder.
Moved A_70_85.png to Anaphase folder.
Moved A_7_29.png to Anaphase folder.
Moved A_96_42.png to Anaphase folder.
Moved B_40_54.png to Anaphase folder.
Moved B_46_67.png to Anaphase folder.
Moved B_69_70.png to Anaphase folder.
Moved C_8_10.png to Anaphase folder.
Moved D_8_16.png to Anaphase folder.
Moved E_5_17.png to Anaphase folder.
Moved E_5_19.png to Anaphase folder.
Moved 001_00027_179.png to Chromosomal aberrations folder.
Moved 001_00035_64.png to Chromosomal aberrations folder.
Moved 001_00078_31.png to Chromosomal aberrations folder.
Moved 002_00007_17.png to Chromosomal aberrations folder.
Moved 002_00039_64.png to Chromosomal aberrations folder.
Moved 002_00040_24.png to Chromosomal aberrations folder.
Moved 002_00046_151.png to Chromosomal aberrations folder.
Moved 002_00047_80.png to Chromosomal aberrations folder.
Moved 002_00057_23.png to Chromosomal aberrations folder.
Moved 002_00063_65.png to Chromosomal aberrations folder.
Moved 002_00067_82.png to Chromosomal aberrations folder.
Moved 003_00010_31.png to Chromosomal aberrations folder.
Moved 003_00044_111.png to Chromosomal aberrations folder.
Moved 003_00060_37.png to Chromosomal aberrations folder.
Moved 003_00061_1.png to Chromosomal aberrations folder.
Moved 003_00061_53.png to Chromosomal aberrations folder.
Moved 003_00067_117.png to Chromosomal aberrations folder.
Moved 003_00067_57.png to Chromosomal aberrations folder.
Moved 003_00068_42.png to Chromosomal aberrations folder.
Moved 003_00081_7.png to Chromosomal aberrations folder.
Moved 004_00006_108.png to Chromosomal aberrations folder.
Moved 004_00009_88.png to Chromosomal aberrations folder.
Moved 004_00010_32.png to Chromosomal aberrations folder.
Moved 004_00013_73.png to Chromosomal aberrations folder.
Moved 004_00026_4.png to Chromosomal aberrations folder.
Moved 004_00028_86.png to Chromosomal aberrations folder.
Moved 004_00030_107.png to Chromosomal aberrations folder.
Moved 004_00039_5.png to Chromosomal aberrations folder.
Moved 004_00041_57.png to Chromosomal aberrations folder.
Moved 004_00042_86.png to Chromosomal aberrations folder.
Moved 004_00049_1.png to Chromosomal aberrations folder.
Moved 004_00050_61.png to Chromosomal aberrations folder.
Moved 004_00054_31.png to Chromosomal aberrations folder.
Moved 004_00066_35.png to Chromosomal aberrations folder.
Moved 004_00078_98.png to Chromosomal aberrations folder.
Moved 004_00088_65.png to Chromosomal aberrations folder.
Moved 004_00090_70.png to Chromosomal aberrations folder.
Moved 004_00091_8.png to Chromosomal aberrations folder.
Moved 004_00101_116.png to Chromosomal aberrations folder.
Moved 004_00102_29.png to Chromosomal aberrations folder.
Moved 004_00103_32.png to Chromosomal aberrations folder.
Moved A_230_52.png to Chromosomal aberrations folder.
Moved A_236_44.png to Chromosomal aberrations folder.
Moved A_252_53.png to Chromosomal aberrations folder.
Moved A_25_51.png to Chromosomal aberrations folder.
Moved A_304_36.png to Chromosomal aberrations folder.
Moved A_308_12.png to Chromosomal aberrations folder.
Moved A_308_46.png to Chromosomal aberrations folder.
Moved A_33_67.png to Chromosomal aberrations folder.
Moved A_349_4.png to Chromosomal aberrations folder.
Moved A_37_27.png to Chromosomal aberrations folder.
Moved A_61_69.png to Chromosomal aberrations folder.
Moved B_117_8.png to Chromosomal aberrations folder.
Moved B_118_8.png to Chromosomal aberrations folder.
Moved B_17_34.png to Chromosomal aberrations folder.
Moved B_20_58.png to Chromosomal aberrations folder.
Moved B_45_20.png to Chromosomal aberrations folder.
Moved B_70_26.png to Chromosomal aberrations folder.
Moved B_79_79.png to Chromosomal aberrations folder.
Moved B_89_42.png to Chromosomal aberrations folder.
Moved C_33_4.png to Chromosomal aberrations folder.
Moved C_45_16.png to Chromosomal aberrations folder.
Moved D_16_9.png to Chromosomal aberrations folder.
Moved D_50_34.png to Chromosomal aberrations folder.
Moved F_24_4.png to Chromosomal aberrations folder.
Moved 001_00027_80.png to Indeterminate folder.
Moved 001_00030_129.png to Indeterminate folder.
Moved 001_00030_24.png to Indeterminate folder.
Moved 001_00030_69.png to Indeterminate folder.
Moved 001_00031_134.png to Indeterminate folder.
Moved 001_00045_15.png to Indeterminate folder.
Moved 001_00060_52.png to Indeterminate folder.
Moved 001_00066_6.png to Indeterminate folder.
Moved 001_00068_117.png to Indeterminate folder.
Moved 001_00069_81.png to Indeterminate folder.
Moved 001_00072_3.png to Indeterminate folder.
Moved 001_00077_55.png to Indeterminate folder.
Moved 001_00082_4.png to Indeterminate folder.
Moved 002_00007_46.png to Indeterminate folder.
Moved 002_00010_38.png to Indeterminate folder.
Moved 002_00021_84.png to Indeterminate folder.
Moved 002_00027_14.png to Indeterminate folder.
Moved 002_00038_58.png to Indeterminate folder.
Moved 002_00039_115.png to Indeterminate folder.
Moved 002_00042_112.png to Indeterminate folder.
Moved 002_00042_52.png to Indeterminate folder.
Moved 002_00044_38.png to Indeterminate folder.
Moved 002_00046_21.png to Indeterminate folder.
Moved 002_00046_65.png to Indeterminate folder.
Moved 002_00047_110.png to Indeterminate folder.
Moved 002_00051_57.png to Indeterminate folder.
Moved 002_00057_46.png to Indeterminate folder.
Moved 002_00058_2.png to Indeterminate folder.
Moved 002_00058_60.png to Indeterminate folder.
Moved 003_00008_44.png to Indeterminate folder.
Moved 003_00009_71.png to Indeterminate folder.
Moved 003_00009_99.png to Indeterminate folder.
Moved 003_00021_59.png to Indeterminate folder.
Moved 003_00025_50.png to Indeterminate folder.
Moved 003_00026_27.png to Indeterminate folder.
Moved 003_00026_50.png to Indeterminate folder.
Moved 003_00043_34.png to Indeterminate folder.
Moved 003_00043_35.png to Indeterminate folder.
Moved 003_00045_0.png to Indeterminate folder.
Moved 003_00045_2.png to Indeterminate folder.
Moved 003_00053_190.png to Indeterminate folder.
Moved 003_00059_14.png to Indeterminate folder.
Moved 003_00063_126.png to Indeterminate folder.
Moved 003_00064_81.png to Indeterminate folder.
Moved 003_00066_47.png to Indeterminate folder.
Moved 003_00068_48.png to Indeterminate folder.
Moved 003_00069_8.png to Indeterminate folder.
Moved 003_00069_88.png to Indeterminate folder.
Moved 003_00070_73.png to Indeterminate folder.
Moved 004_00006_13.png to Indeterminate folder.
Moved 004_00007_70.png to Indeterminate folder.
Moved 004_00007_78.png to Indeterminate folder.
Moved 004_00027_0.png to Indeterminate folder.
Moved 004_00027_48.png to Indeterminate folder.
Moved 004_00028_120.png to Indeterminate folder.
Moved 004_00028_121.png to Indeterminate folder.
Moved 004_00032_29.png to Indeterminate folder.
Moved 004_00034_162.png to Indeterminate folder.
Moved 004_00037_35.png to Indeterminate folder.
Moved 004_00041_105.png to Indeterminate folder.
Moved 004_00050_177.png to Indeterminate folder.
Moved 004_00059_86.png to Indeterminate folder.
Moved 004_00068_13.png to Indeterminate folder.
Moved 004_00070_77.png to Indeterminate folder.
Moved 004_00071_45.png to Indeterminate folder.
Moved 004_00074_128.png to Indeterminate folder.
Moved 004_00074_15.png to Indeterminate folder.
Moved 004_00075_92.png to Indeterminate folder.
Moved 004_00076_28.png to Indeterminate folder.
Moved 004_00076_49.png to Indeterminate folder.
Moved 004_00077_16.png to Indeterminate folder.
Moved 004_00078_0.png to Indeterminate folder.
Moved 004_00078_162.png to Indeterminate folder.
Moved 004_00080_193.png to Indeterminate folder.
Moved 004_00081_129.png to Indeterminate folder.
Moved 004_00081_3.png to Indeterminate folder.
Moved 004_00085_76.png to Indeterminate folder.
Moved 004_00087_92.png to Indeterminate folder.
Moved 004_00090_77.png to Indeterminate folder.
Moved 004_00090_8.png to Indeterminate folder.
Moved 004_00092_84.png to Indeterminate folder.
Moved 004_00093_33.png to Indeterminate folder.
Moved 004_00101_44.png to Indeterminate folder.
Moved 004_00101_91.png to Indeterminate folder.
Moved 004_00102_7.png to Indeterminate folder.
Moved A_105_76.png to Indeterminate folder.
Moved A_134_31.png to Indeterminate folder.
Moved A_249_8.png to Indeterminate folder.
Moved A_26_73.png to Indeterminate folder.
Moved A_33_60.png to Indeterminate folder.
Moved A_382_11.png to Indeterminate folder.
Moved A_51_57.png to Indeterminate folder.
Moved A_52_45.png to Indeterminate folder.
Moved A_67_21.png to Indeterminate folder.
Moved A_71_21.png to Indeterminate folder.
Moved A_82_14.png to Indeterminate folder.
Moved A_85_12.png to Indeterminate folder.
Moved A_86_13.png to Indeterminate folder.
Moved B_21_9.png to Indeterminate folder.
Moved B_50_34.png to Indeterminate folder.
Moved C_3_5.png to Indeterminate folder.
Moved E_6_20.png to Indeterminate folder.
Moved 001_00027_55.png to Interphase folder.
Moved 001_00034_83.png to Interphase folder.
Moved 001_00034_95.png to Interphase folder.
Moved 001_00036_21.png to Interphase folder.
Moved 001_00039_156.png to Interphase folder.
Moved 001_00042_70.png to Interphase folder.
Moved 001_00056_31.png to Interphase folder.
Moved 001_00056_37.png to Interphase folder.
Moved 001_00069_92.png to Interphase folder.
Moved 002_00015_87.png to Interphase folder.
Moved 002_00019_2.png to Interphase folder.
Moved 002_00022_104.png to Interphase folder.
Moved 002_00022_18.png to Interphase folder.
Moved 002_00037_1.png to Interphase folder.
Moved 002_00037_116.png to Interphase folder.
Moved 002_00046_159.png to Interphase folder.
Moved 002_00051_117.png to Interphase folder.
Moved 002_00051_153.png to Interphase folder.
Moved 002_00051_65.png to Interphase folder.
Moved 002_00055_174.png to Interphase folder.
Moved 002_00063_32.png to Interphase folder.
Moved 003_00004_20.png to Interphase folder.
Moved 003_00009_111.png to Interphase folder.
Moved 003_00009_125.png to Interphase folder.
Moved 003_00010_80.png to Interphase folder.
Moved 003_00017_31.png to Interphase folder.
Moved 003_00017_58.png to Interphase folder.
Moved 003_00021_2.png to Interphase folder.
Moved 003_00021_30.png to Interphase folder.
Moved 003_00021_84.png to Interphase folder.
Moved 003_00021_94.png to Interphase folder.
Moved 003_00023_123.png to Interphase folder.
Moved 003_00025_13.png to Interphase folder.
Moved 003_00025_18.png to Interphase folder.
Moved 003_00025_22.png to Interphase folder.
Moved 003_00025_27.png to Interphase folder.
Moved 003_00025_40.png to Interphase folder.
Moved 003_00025_58.png to Interphase folder.
Moved 003_00025_67.png to Interphase folder.
Moved 003_00026_57.png to Interphase folder.
Moved 003_00028_45.png to Interphase folder.
Moved 003_00028_46.png to Interphase folder.
Moved 003_00031_44.png to Interphase folder.
Moved 003_00042_26.png to Interphase folder.
Moved 003_00042_27.png to Interphase folder.
Moved 003_00043_23.png to Interphase folder.
Moved 003_00043_26.png to Interphase folder.
Moved 003_00043_30.png to Interphase folder.
Moved 003_00044_18.png to Interphase folder.
Moved 003_00044_37.png to Interphase folder.
Moved 003_00044_41.png to Interphase folder.
Moved 003_00044_52.png to Interphase folder.
Moved 003_00044_55.png to Interphase folder.
Moved 003_00052_13.png to Interphase folder.
Moved 003_00052_20.png to Interphase folder.
Moved 003_00052_32.png to Interphase folder.
Moved 003_00057_187.png to Interphase folder.
Moved 003_00059_62.png to Interphase folder.
Moved 003_00060_97.png to Interphase folder.
Moved 003_00061_82.png to Interphase folder.
Moved 003_00063_31.png to Interphase folder.
Moved 003_00064_0.png to Interphase folder.
Moved 003_00066_2.png to Interphase folder.
Moved 003_00067_18.png to Interphase folder.
Moved 003_00067_3.png to Interphase folder.
Moved 003_00067_40.png to Interphase folder.
Moved 003_00067_43.png to Interphase folder.
Moved 003_00068_39.png to Interphase folder.
Moved 003_00069_29.png to Interphase folder.
Moved 003_00069_51.png to Interphase folder.
Moved 003_00069_6.png to Interphase folder.
Moved 003_00069_62.png to Interphase folder.
Moved 003_00070_7.png to Interphase folder.
Moved 003_00073_22.png to Interphase folder.
Moved 003_00080_105.png to Interphase folder.
Moved 003_00080_11.png to Interphase folder.
Moved 003_00081_12.png to Interphase folder.
Moved 004_00001_88.png to Interphase folder.
Moved 004_00004_19.png to Interphase folder.
Moved 004_00004_27.png to Interphase folder.
Moved 004_00006_5.png to Interphase folder.
Moved 004_00010_18.png to Interphase folder.
Moved 004_00012_12.png to Interphase folder.
Moved 004_00014_19.png to Interphase folder.
Moved 004_00019_45.png to Interphase folder.
Moved 004_00019_62.png to Interphase folder.
Moved 004_00025_3.png to Interphase folder.
Moved 004_00027_116.png to Interphase folder.
Moved 004_00027_41.png to Interphase folder.
Moved 004_00028_104.png to Interphase folder.
Moved 004_00028_88.png to Interphase folder.
Moved 004_00028_98.png to Interphase folder.
Moved 004_00029_1.png to Interphase folder.
Moved 004_00029_42.png to Interphase folder.
Moved 004_00031_11.png to Interphase folder.
Moved 004_00037_121.png to Interphase folder.
Moved 004_00037_36.png to Interphase folder.
Moved 004_00041_24.png to Interphase folder.
Moved 004_00041_35.png to Interphase folder.
Moved 004_00042_1.png to Interphase folder.
Moved 004_00043_16.png to Interphase folder.
Moved 004_00046_54.png to Interphase folder.
Moved 004_00049_52.png to Interphase folder.
Moved 004_00049_9.png to Interphase folder.
Moved 004_00050_28.png to Interphase folder.
Moved 004_00050_72.png to Interphase folder.
Moved 004_00056_17.png to Interphase folder.
Moved 004_00056_40.png to Interphase folder.
Moved 004_00059_23.png to Interphase folder.
Moved 004_00059_45.png to Interphase folder.
Moved 004_00059_52.png to Interphase folder.
Moved 004_00059_61.png to Interphase folder.
Moved 004_00066_105.png to Interphase folder.
Moved 004_00066_29.png to Interphase folder.
Moved 004_00074_39.png to Interphase folder.
Moved 004_00076_38.png to Interphase folder.
Moved 004_00076_80.png to Interphase folder.
Moved 004_00077_73.png to Interphase folder.
Moved 004_00081_58.png to Interphase folder.
Moved 004_00083_54.png to Interphase folder.
Moved 004_00084_34.png to Interphase folder.
Moved 004_00085_3.png to Interphase folder.
Moved 004_00088_58.png to Interphase folder.
Moved 004_00101_117.png to Interphase folder.
Moved 004_00101_56.png to Interphase folder.
Moved 004_00102_31.png to Interphase folder.
Moved 004_00102_39.png to Interphase folder.
Moved A_101_4.png to Interphase folder.
Moved A_104_60.png to Interphase folder.
Moved A_10_17.png to Interphase folder.
Moved A_114_36.png to Interphase folder.
Moved A_14_22.png to Interphase folder.
Moved A_14_58.png to Interphase folder.
Moved A_14_60.png to Interphase folder.
Moved A_14_76.png to Interphase folder.
Moved A_15_23.png to Interphase folder.
Moved A_15_63.png to Interphase folder.
Moved A_17_10.png to Interphase folder.
Moved A_17_23.png to Interphase folder.
Moved A_17_37.png to Interphase folder.
Moved A_17_5.png to Interphase folder.
Moved A_17_6.png to Interphase folder.
Moved A_17_67.png to Interphase folder.
Moved A_17_81.png to Interphase folder.
Moved A_18_24.png to Interphase folder.
Moved A_18_51.png to Interphase folder.
Moved A_18_60.png to Interphase folder.
Moved A_18_93.png to Interphase folder.
Moved A_19_26.png to Interphase folder.
Moved A_20_24.png to Interphase folder.
Moved A_20_97.png to Interphase folder.
Moved A_211_17.png to Interphase folder.
Moved A_213_0.png to Interphase folder.
Moved A_21_44.png to Interphase folder.
Moved A_21_63.png to Interphase folder.
Moved A_226_29.png to Interphase folder.
Moved A_23_12.png to Interphase folder.
Moved A_23_13.png to Interphase folder.
Moved A_23_19.png to Interphase folder.
Moved A_23_24.png to Interphase folder.
Moved A_23_29.png to Interphase folder.
Moved A_23_30.png to Interphase folder.
Moved A_23_37.png to Interphase folder.
Moved A_23_4.png to Interphase folder.
Moved A_240_2.png to Interphase folder.
Moved A_24_10.png to Interphase folder.
Moved A_24_13.png to Interphase folder.
Moved A_24_17.png to Interphase folder.
Moved A_24_28.png to Interphase folder.
Moved A_24_33.png to Interphase folder.
Moved A_24_34.png to Interphase folder.
Moved A_24_36.png to Interphase folder.
Moved A_24_41.png to Interphase folder.
Moved A_24_44.png to Interphase folder.
Moved A_24_49.png to Interphase folder.
Moved A_24_6.png to Interphase folder.
Moved A_24_62.png to Interphase folder.
Moved A_250_13.png to Interphase folder.
Moved A_250_14.png to Interphase folder.
Moved A_255_15.png to Interphase folder.
Moved A_265_10.png to Interphase folder.
Moved A_267_50.png to Interphase folder.
Moved A_269_10.png to Interphase folder.
Moved A_276_15.png to Interphase folder.
Moved A_284_29.png to Interphase folder.
Moved A_285_54.png to Interphase folder.
Moved A_2_0.png to Interphase folder.
Moved A_2_49.png to Interphase folder.
Moved A_306_0.png to Interphase folder.
Moved A_325_21.png to Interphase folder.
Moved A_326_42.png to Interphase folder.
Moved A_332_13.png to Interphase folder.
Moved A_333_13.png to Interphase folder.
Moved A_340_1.png to Interphase folder.
Moved A_341_21.png to Interphase folder.
Moved A_355_24.png to Interphase folder.
Moved A_37_32.png to Interphase folder.
Moved A_3_16.png to Interphase folder.
Moved A_3_23.png to Interphase folder.
Moved A_3_34.png to Interphase folder.
Moved A_3_36.png to Interphase folder.
Moved A_3_50.png to Interphase folder.
Moved A_3_58.png to Interphase folder.
Moved A_40_75.png to Interphase folder.
Moved A_40_90.png to Interphase folder.
Moved A_40_91.png to Interphase folder.
Moved A_45_8.png to Interphase folder.
Moved A_4_50.png to Interphase folder.
Moved A_50_7.png to Interphase folder.
Moved A_5_64.png to Interphase folder.
Moved A_5_77.png to Interphase folder.
Moved A_62_25.png to Interphase folder.
Moved A_6_14.png to Interphase folder.
Moved A_6_2.png to Interphase folder.
Moved A_70_33.png to Interphase folder.
Moved A_76_18.png to Interphase folder.
Moved A_7_62.png to Interphase folder.
Moved A_85_18.png to Interphase folder.
Moved B_102_19.png to Interphase folder.
Moved B_103_14.png to Interphase folder.
Moved B_103_17.png to Interphase folder.